extends: airbnb
env:
  browser: true
  es6: true
  node: true
  mocha: true
rules:
  global-require: 0
  import/extensions: 0
  react/forbid-prop-types: 1
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/no-autofocus: 0
  react/destructuring-assignment: 0
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/click-events-have-key-events: 0